# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 798043d9c454d0ff10eb3377cfa24e093cc899209e5c3f56e07982a89b2f4a684daedb753162a4a6cb393199645f0a15821c808c1ba49c720dac4db9d859eed1

test:
  secret_key_base: d180e255ba7ee23a5549f23bc158a3117f3374d9e2c0c0730b497ad060e942f17c76c9f7bc46194d5b71110e8e18eb69c096e5c58c494c9d447d9df3fc7eeb07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
